### ISSUE TITLE
Distro - SPI hooks

### ISSUE THREAD

**Issue by jamesylgan** [signalfx/splunk-otel-java#71] opened 2021-01-05 15:30 UTC
I am wondering - when are SPI hooks like [this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/examples/distro/custom/src/main/resources/META-INF/services/io.opentelemetry.javaagent.spi.TracerCustomizer) required? Would you need a similar ...spi.PropagatorCustomizer file for the [DemoPropagator](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/examples/distro/custom/src/main/java/com/example/javaagent/DemoPropagator.java)?

In a distribution - I want to add a custom propagator. What all are the steps required? It seems like there is no clear answer yet. Is there some documentation detailing how the build process of the distribution works?

@iNikem - also asked here (https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/1975) for reference

**Comment by vovencij** [comment] 2021-01-06 13:16
This repo has some examples of how such customizers can be used:

- Pre-configuring sampling: https://github.com/signalfx/splunk-otel-java/blob/main/custom/src/main/java/com/splunk/opentelemetry/SplunkTracerCustomizer.java
- Registering custom span processor: https://github.com/signalfx/splunk-otel-java/blob/main/custom/src/main/java/com/splunk/opentelemetry/middleware/MiddlewareTracerCustomizer.java

**Comment by vovencij** [comment] 2021-01-06 13:24
And custom propagator registration is done via TracerCustomizer, like here:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/examples/distro/custom/src/main/java/com/example/javaagent/DemoTracerCustomizer.java#L35

**Comment by jamesylgan** [comment] 2021-01-06 20:20
That's great! Any way for us to document the link from your second comment as how someone would link in a custom propagator? I think it would be valuable to include

**Comment by vovencij** [comment] 2021-01-07 09:19
I believe this kind of documentation should go to `opentelemetry-java-instrumentation` project, under `examples/distro`. I suggest you file an issue for improved custom distro documentation there and we close this particular ticket.

**Comment by sparam** [comment] 2021-01-08 08:22
Hi @vovencij @iNikem 

I am using splunk otel version 0.12.0 and trying to add custom propagation.

<img width="1015" alt="Screen Shot 2021-01-08 at 12 17 30 AM" src="https://user-images.githubusercontent.com/1302580/103991017-f7176c00-5146-11eb-9bb4-ad058c3b0abc.png">

resources/META-INF/services/io.opentelemetry.javaagent.spi.TracerCustomizer
```
com.splunk.opentelemetry.SplunkTracerCustomizer
com.splunk.opentelemetry.DemoTracerCustomizer

```
After build and including the otel java agent as part of the application for instrumentation, I am seeing below error:

`Caused by: java.lang.IllegalArgumentException: The OpenTelemetrySdk can only be configured with a TracerSdkProvider
	at io.opentelemetry.sdk.OpenTelemetrySdk$Builder.setTracerProvider(OpenTelemetrySdk.java:135)
	at io.opentelemetry.sdk.OpenTelemetrySdk.toBuilder(OpenTelemetrySdk.java:105)
	at com.splunk.opentelemetry.DemoTracerCustomizer.configure(DemoTracerCustomizer.java:16)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.configure(TracerInstaller.java:205)
	at io.opentelemetry.javaagent.tooling.TracerInstaller.installAgentTracer(TracerInstaller.java:48)
`

**Note:** 
The demo/example documented here https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/examples/distro/custom/src/main/java/com/example/javaagent/DemoTracerCustomizer.java#L35 is part of Opentelemetry  0.13.0. But splunk otel still uses 0.12.0. Should Splunk update to version 0.13.0 of opentelemetry to get the latest version of the TracerCustomizer? so that it fixes the deprecated code and other changes from the TracerCustomizer.

**Comment by vovencij** [comment] 2021-01-08 09:20
Current HEAD in git is already updated to otel-java/instrumentation 0.13. It's just not yet released. The release should happen during next week the latest.

**Comment by vovencij** [comment] 2021-01-08 14:10
@sparam Splunk distro 0.5.0 was released today. Give it a try!

**Comment by sparam** [comment] 2021-01-08 16:12
@vovencij . Will give it a try. I assume we need 0.13 to resolve the error I observed? Thanks!

**Comment by vovencij** [comment] 2021-01-11 08:43
Yes, you have to keep the agent and versions of opentelemetry libraries in sync.

**Comment by iNikem** [comment] 2021-04-05 07:25
@jamesylgan @sparam Should anything be done regarding this issue? It seems to me that there is no call to action here :) I would like to close it.

If you have any more questions about customising Otel java distribution, please open a new discussion for that.

**Comment by jamesylgan** [comment] 2021-04-08 15:50
@iNikem This method seems to have changed in recent releases. I'd say the main action item is **adding documentation for how-to add custom propagator**

**Closed** 2021-04-08 15:50 UTC
